/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pakiet;

//import pakiet.*;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Date;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dominik
 */
public class GUI extends javax.swing.JFrame {
     Functions f; //obiekt f będzie dostarczał wszystkich niezbędnych funkcji
    
    /**
     * Creates new form GUI
     */
    public GUI() throws IOException, FileNotFoundException, SQLException {
        initComponents();
        f= new Functions();
        jPanelZaloguj.setVisible(false);
        jPanelZarejestruj.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanelZarejestruj = new javax.swing.JPanel();
        jLabelImie = new javax.swing.JLabel();
        jLabelNazwisko = new javax.swing.JLabel();
        jTextFieldImie = new javax.swing.JTextField();
        jTextFieldNazwisko = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldLoginRej = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldHasloZar2 = new javax.swing.JTextField();
        jTextFieldHasloZar = new javax.swing.JTextField();
        jButtonZarOk = new javax.swing.JButton();
        jPanelZaloguj = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldLoginZal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldHasloZal = new javax.swing.JTextField();
        jToggleButtonLogujOk = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItemWyloguj = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelImie.setText("Imię:");

        jLabelNazwisko.setText("Nazwisko:");

        jTextFieldNazwisko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNazwiskoActionPerformed(evt);
            }
        });

        jLabel4.setText("Adres E-mail:");

        jLabel5.setText("Login:");

        jLabel6.setText("Hasło:");

        jLabel7.setText("Powtórz hasło:");

        jButtonZarOk.setText("Ok");
        jButtonZarOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZarOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelZarejestrujLayout = new javax.swing.GroupLayout(jPanelZarejestruj);
        jPanelZarejestruj.setLayout(jPanelZarejestrujLayout);
        jPanelZarejestrujLayout.setHorizontalGroup(
            jPanelZarejestrujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelZarejestrujLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelZarejestrujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelZarejestrujLayout.createSequentialGroup()
                        .addGroup(jPanelZarejestrujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(jPanelZarejestrujLayout.createSequentialGroup()
                                .addGroup(jPanelZarejestrujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(41, 41, 41)
                                .addGroup(jPanelZarejestrujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldHasloZar, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                    .addComponent(jTextFieldHasloZar2))))
                        .addContainerGap(175, Short.MAX_VALUE))
                    .addGroup(jPanelZarejestrujLayout.createSequentialGroup()
                        .addGroup(jPanelZarejestrujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelZarejestrujLayout.createSequentialGroup()
                                .addGroup(jPanelZarejestrujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelImie)
                                    .addComponent(jLabelNazwisko))
                                .addGap(65, 65, 65)
                                .addGroup(jPanelZarejestrujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldNazwisko)
                                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(jTextFieldLoginRej)
                                    .addComponent(jTextFieldImie)))
                            .addComponent(jButtonZarOk))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelZarejestrujLayout.setVerticalGroup(
            jPanelZarejestrujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelZarejestrujLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelZarejestrujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelImie)
                    .addComponent(jTextFieldImie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelZarejestrujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNazwisko)
                    .addComponent(jTextFieldNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelZarejestrujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelZarejestrujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldLoginRej, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelZarejestrujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldHasloZar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelZarejestrujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldHasloZar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonZarOk)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        //jPanelZaloguj.setEnabled(false);

        jLabel2.setText("Login:");

        jLabel3.setText("Hasło:");

        jToggleButtonLogujOk.setText("Ok");
        jToggleButtonLogujOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonLogujOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelZalogujLayout = new javax.swing.GroupLayout(jPanelZaloguj);
        jPanelZaloguj.setLayout(jPanelZalogujLayout);
        jPanelZalogujLayout.setHorizontalGroup(
            jPanelZalogujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelZalogujLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelZalogujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelZalogujLayout.createSequentialGroup()
                        .addGroup(jPanelZalogujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addGroup(jPanelZalogujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldHasloZal, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLoginZal, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jToggleButtonLogujOk))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        jPanelZalogujLayout.setVerticalGroup(
            jPanelZalogujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelZalogujLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelZalogujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldLoginZal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelZalogujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldHasloZal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtonLogujOk)
                .addContainerGap(217, Short.MAX_VALUE))
        );

        jMenu1.setText("Użytkownik");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem1.setText("Zaloguj");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem2.setText("Zarejestruj");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItemWyloguj.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemWyloguj.setText("Wyloguj");
        jMenuItemWyloguj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemWylogujActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemWyloguj);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelZaloguj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelZarejestruj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelZaloguj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelZarejestruj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jPanelZaloguj.setVisible(false);
        jPanelZarejestruj.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jPanelZaloguj.setVisible(true);
        jPanelZarejestruj.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemWylogujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemWylogujActionPerformed
        jPanelZaloguj.setVisible(false);
        jPanelZarejestruj.setVisible(false);
    }//GEN-LAST:event_jMenuItemWylogujActionPerformed

    private void jToggleButtonLogujOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonLogujOkActionPerformed
        
        
        
        try {
            //Odczytanie danych z formularza
            String login = jTextFieldLoginZal.getText();
            String password = jTextFieldHasloZal.getText();
            String encryptedPassword = f.encrypt(password);
            
            if(login.equals("")) throw new Exception();//jeśli nie podano loginu to koniec logowania
            
            //System.out.println(encryptedPassword);
        
            /*if(hasz.compare("ddjd", "ddd")==true) System.out.println("Równe");
            else System.out.println("Nie Równe");//test compare()*/
            
            //nawiązanie połączenia
            
            //sprawdzenie czy użytkownik istnieje
            User user = f.getUser(login);
            String usersPassword = user.getPassword();
            if(f.compare(encryptedPassword, usersPassword)){
                JOptionPane.showMessageDialog(null, "Zalogowano na konto użytkownika " + user.getLogin());
            }
            else{
                JOptionPane.showMessageDialog(null, "Złe hasło");
            }
            
        } catch (Exception ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Nie ma takiego użytkownika");
        }
    }//GEN-LAST:event_jToggleButtonLogujOkActionPerformed

    private void jTextFieldNazwiskoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNazwiskoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNazwiskoActionPerformed

    private void jButtonZarOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZarOkActionPerformed
        //Rejestracja nowego użytkownika
        
        //Zebranie danych
        String login = jTextFieldLoginRej.getText();
        try {
            if(f.userExist(login)){
                throw new SQLException();
            }
            
            String imie = jTextFieldImie.getText();
            String nazwisko = jTextFieldNazwisko.getText();
            String email = jTextFieldEmail.getText();
            
           //Porównianie haseł
           String haslo1 = jTextFieldHasloZar.getText();
           String haslo2 = jTextFieldHasloZar2.getText(); 
           if(!haslo1.equals(haslo2)){
               throw new SQLException();
           }
           //Date czas = new Date(System.currentTimeMillis());
           //Enkrytpowanie hasła
           haslo1 = f.encrypt(haslo1);
           //tworzenie nowego usera
           User user = new User(login, haslo1, imie, nazwisko, email);//,czas);
           //System.out.print(czas);
           // i dodwanie go do bazy
           f.addUser(user);
           
           
        
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Użytkownik o podanym loginie już istnieje lub hasła są różne");
        }
       
     
        
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Podane hasła są różne");
        }
        
        
    }//GEN-LAST:event_jButtonZarOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GUI().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonZarOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelImie;
    private javax.swing.JLabel jLabelNazwisko;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemWyloguj;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelZaloguj;
    private javax.swing.JPanel jPanelZarejestruj;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldHasloZal;
    private javax.swing.JTextField jTextFieldHasloZar;
    private javax.swing.JTextField jTextFieldHasloZar2;
    private javax.swing.JTextField jTextFieldImie;
    private javax.swing.JTextField jTextFieldLoginRej;
    private javax.swing.JTextField jTextFieldLoginZal;
    private javax.swing.JTextField jTextFieldNazwisko;
    private javax.swing.JToggleButton jToggleButtonLogujOk;
    // End of variables declaration//GEN-END:variables
}
